name: Hassfest

on:
  push:
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Run Hassfest
        uses: home-assistant/actions/hassfest@master

